#!/bin/bash
BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(main|master|(feature|bug-fix|hot-fix|refactor|types|lint|chore)(\/[a-z0-9]+(-[a-z0-9]+)*))$"

if ! [[ $COMMIT_MESSAGE == *$MERGE_MESSAGE* ]]; then
  if ! [[ $COMMIT_MESSAGE =~ $REGEX ]]; then
    echo "Seu commit foi rejeitado pois não segue os padrões definidos pela equipe."
    echo "Por favor, altere a mensagem de commit para fix|types|feat|lint|refact|chore|test (este escopo é opcional): alguma coisa"
    exit 1
  fi
fi
